---
- include_tasks: apt-stuff.yml
- include_tasks: go-tools.yml
- include_tasks: github-repos.yml
- include_tasks: python-tools.yml
- include_tasks: gem-tools.yml
# - include_tasks: mobile-testing.yml
- include_tasks: docker.yml
- include_tasks: docker-tools.yml
- include_tasks: obsidian.yml
- include_tasks: kubectl.yml
- include_tasks: cyber-chef.yml
